name: temple_and_webster
version: '1.0.0'
config-version: 2

profile: temple_and_webster

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Job schedule will be set up to run the staging models first, followed by the analytics models daily.
# The staging models will be materialized as views, while the analytics models will be materialized as tables.
models:
  temple_and_webster:
    staging:
      +materialized: view
    analytics:
      +materialized: table